name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_explorer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Navigate to Backend Directory
      run: cd backend
    - uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install
    - name: Type check
      run: bun run tsc --noEmit
    - name: Prisma Migrate
      run: |
        export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/db_explorer"
        bun run prisma migrate deploy
    - name: Run tests
      run: |
        export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/db_explorer"
        bun test --coverage
    - name: Clean up
      run: |
        bun cache clean
        bun uninstall
    - name: Drop database
      run: |
        psql -U postgres -c "DROP DATABASE db_explorer;"

